version: '3.6'

services:
  jfrog:
    image: docker.bintray.io/jfrog/jfrog-cli-go
    volumes:
        - .:/work
    working_dir: /work
    environment: 
        - JFROG_CLI_OFFER_CONFIG=false

  buildkite-agent:
    image: buildkite-agent-plus
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock"
        - /var/lib/buildkite/builds:/var/lib/buildkite/builds
        - /usr/local/bin/buildkite-agent:/usr/local/bin/buildkite-agent
    working_dir: /work
    environment:
        - BUILDKITE_AGENT_TOKEN=927dcada0324cd357f5342486073fe70c1d98d7b3aaee8f92b
        - BUILDKITE_BUILD_PATH=/var/lib/buildkite/builds
